openapi: 3.0.0
info:
  title: Learning Management System API
  version: 1.0.0
  description: API for a learning managment platform with courses, mentors, students, and admins;

servers:
  - url: NOT_YET

paths:
  /login:
    post:
      summary: User login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
                  enum: [student, mentor, admin]
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

  /signup:
    post:
      summary: User registration
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
                  enum: [student, mentor]
                fname:
                  type: string
                lname:
                  type: string
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                passwordConfirm:
                  type: string

      responses:
        "201":
          description: User created

  /student:
    get:
      summary: get all student info [profile, courses, chats, messages, mentors]
      tags:
        - Student
      security:
        - BearerAuth: []

      responses:
        "200":
          description: Success
  /student/profile:
    get:
      summary: get student profile
      tags:
        - Student
      security:
        - BearerAuth: []

      responses:
        "200":
          description: Success
    put:
      summary: Update student profile
      tags:
        - Student
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CourseInput"
      responses:
        "200":
          description: Updating done
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Course"

  /student/chats:
    get:
      summary: get student chats
      tags:
        - Student
      security:
        - BearerAuth: []

      responses:
        "200":
          description: Success

  /student/messages:
    get:
      summary: get student messages
      tags:
        - Student
      security:
        - BearerAuth: []

      responses:
        "200":
          description: Success

  /student/courses:
    get:
      summary: get all student courses [enrolled, archived, cart, wishlist]
      tags:
        - Student
      security:
        - BearerAuth: []

      responses:
        "200":
          description: Success
  /student/courses/enrolled:
    get:
      summary: get student enrolled courses
      tags:
        - Student
      security:
        - BearerAuth: []

      responses:
        "200":
          description: Success
    post:
      summary: Enroll into a new course
      tags:
        - Student
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CourseInput"
      responses:
        "201":
          description: Enrolled done
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Course"

  /student/courses/archived:
    get:
      summary: get student archived courses
      tags:
        - Student
      security:
        - BearerAuth: []

      responses:
        "200":
          description: Success
    post:
      summary: Arvhive an enrolled course
      tags:
        - Student
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CourseInput"
      responses:
        "201":
          description: Archiving done
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Course"
  /student/courses/cart:
    get:
      summary: get student cart courses
      tags:
        - Student
      security:
        - BearerAuth: []

      responses:
        "200":
          description: Success
    post:
      summary: Add a new course into the cart
      tags:
        - Student
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CourseInput"
      responses:
        "201":
          description: Addition done
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Course"
  /student/courses/wishlist:
    get:
      summary: get student wishlist courses
      tags:
        - Student
      security:
        - BearerAuth: []

      responses:
        "200":
          description: Success
    post:
      summary: Add a course into the wishlist
      tags:
        - Student
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CourseInput"
      responses:
        "201":
          description: Addition done
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Course"

  /mentor:
    get:
      summary: get all mentor info [profile, courses, reviews, chats, coupouns]
      tags:
        - Mentor
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Success

  /mentor/profile/:
    get:
      summary: get mentor profile
      tags:
        - Mentor
      responses:
        "200":
          description: Success

  /mentor/student-reviews/:
    get:
      summary: get mentor student reviews
      tags:
        - Mentor
      responses:
        "200":
          description: Success

  /mentor/chats/:
    get:
      summary: Get mentor chats
      tags:
        - Mentor
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Success

  /mentor/courses/:
    get:
      summary: Get mentor courses
      tags:
        - Mentor
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Success
    post:
      summary: Add new course
      tags:
        - Mentor
      security:
        - BearerAuth: []
      responses:
        "201":
          description: Addition done
    put:
      summary: Update course
      tags:
        - Mentor
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Update done
    delete:
      summary: Delete course
      tags:
        - Mentor
      security:
        - BearerAuth: []
      responses:
        "204":

  /mentor/copouns/:
    get:
      summary: Get mentor copouns
      tags:
        - Mentor
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Success
    post:
      summary: Add mentor copouns
      tags:
        - Mentor
      security:
        - BearerAuth: []
      responses:
        "201":
          description: Addition done
    put:
      summary: Update mentor copouns
      tags:
        - Mentor
      security:
        - BearerAuth: []
      responses:
        "201":
          description: Update done
    delete:
      summary: Delete mentor copouns
      tags:
        - Mentor
      security:
        - BearerAuth: []
      responses:
        "204":

  /courses:
    get:
      summary: Get all courses
      tags:
        - Courses
      responses:
        "200":
          description: Course have been created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Course"

    post:
      summary: Create one
      tags:
        - Courses
      responses:
        "201":
          description: Course have been created
          content:
            application/json:
              schema:
                type: object
                items:
                  $mentorRe: "Mentor"
                  $title: string
                  $titleHook: string
                  $levels: string
                  $languages: string
                  $whatYoulLearn: string
                  $tags: string
                  $requirements: string
                  $description: string
                  $modules:
                    $title: string
                    $lessons:
                      $title: stirng
                      $srcVideo: string
                      $content: string
                  $photo: ""
                  $price: ""

  /course:
    get:
      summary: Get all courses
      tags:
        - Courses
      responses:
        "200":
          description: List of courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Course"

  /top:
    get:
      summary: Get all top stats [categouries, stats, courses, mentors, comments]
      tags:
        - Top
      responses:
        "200":
          description: Success

  /top/stats:
    get:
      summary: Get top stats numbers
      tags:
        - Top
      responses:
        "200":
          description: Success

  /top/categouries:
    get:
      summary: Get top categouries
      tags:
        - Top
      responses:
        "200":
          description: Success

  /top/courses:
    get:
      summary: Get top courses
      tags:
        - Top
      responses:
        "200":
          description: Success

  /top/mentors:
    get:
      summary: Get top mentors
      tags:
        - Top
      responses:
        "200":
          description: Success

  /top/comments:
    get:
      summary: Get top comments
      tags:
        - Top
      responses:
        "200":
          description: Success

  /admin/students:
    get:
      summary: get students
      tags:
        - Admin
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Success

  /admin/mentors:
    get:
      summary: get students
      tags:
        - Admin
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Success
